# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ttimer.ttimer
PackageVersion: "1.0"
InstallerType: zip
NestedInstallerType: exe
NestedInstallerFiles:
- RelativeFilePath: ttimer.exe
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/MaxCoteLeKing/ttimer/releases/download/WinGet/ttimer.zip
  InstallerSha256: 707fb785a69e99426daf69cfe6eb9c328f72055a071eb8b4ef85d10b190ce73e
  InstallerSwitches:
    Custom: --install
ManifestType: installer
ManifestVersion: 1.6.0
